#!/usr/bin/env python3
"""
Script to extract features from bounding boxes generated by the DocStrum pipeline.

Usage:
    python extract_docstrum_features.py \
        --docstrum-json path/to/docstrum_output.json \
        --image-dir path/to/images/ \
        --output-dir path/to/save/features/
"""
import os
import argparse
from feature_extraction import save_features


def main():
    parser = argparse.ArgumentParser(
        description="Extract features for bounding boxes from DocStrum output JSON."
    )
    parser.add_argument(
        "--docstrum-json", required=True,
        help="Path to the DocStrum output COCO JSON file."
    )
    parser.add_argument(
        "--image-dir", required=True,
        help="Directory containing the document images."
    )
    parser.add_argument(
        "--output-dir", default=".",
        help="Directory to save the features CSV."
    )
    args = parser.parse_args()

    # Extract and save features
    df = save_features(
        json_path=args.docstrum_json,
        image_dir=args.image_dir,
        output_dir=args.output_dir
    )

    out_csv = os.path.join(
        args.output_dir,
        f"features_{os.path.splitext(os.path.basename(args.docstrum_json))[0]}.csv"
    )
    print(f"[✓] Feature extraction complete: {len(df)} regions saved to {out_csv}")


if __name__ == "__main__":
    main()
